// Generated by cbindgen. Do not edit by hand.
// FFI surface for embedding plotly-client in the iOS app shell (see src/ios.rs).

#ifndef KIWI_CLIENT_H
#define KIWI_CLIENT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Starts the HTTP server (bound to `127.0.0.1:http_port`) and the UDP listener
 * (bound to `0.0.0.0:udp_port`) on a background thread. Returns immediately; poll
 * `http://127.0.0.1:<http_port>/devices` from Swift to detect readiness, matching the desktop
 * Electron shell's startup pattern.
 *
 * Returns 0 on success, -1 if a server is already running.
 */
int32_t kiwi_start(uint16_t http_port, uint16_t udp_port);

/**
 * Gracefully stops a server started with [`kiwi_start`]. No-op if none is running.
 */
void kiwi_stop(void);

#endif  /* KIWI_CLIENT_H */
